#!/bin/bash

EXAMPLES_DIR="examples"

EXAMPLES=$(ls -1 $EXAMPLES_DIR)

MK="./load-examples.mk"

echo "# Auto-generated by $(basename $0)" > $MK

for i in $EXAMPLES
do
  if [[ -d "$EXAMPLES_DIR/$i" ]]; then
    echo "example found: $i"

    echo "example-$i:" >> $MK
    echo -e "\tln -sf examples/$i/* . " >> $MK
    echo "" >> $MK

  else
    echo "this is not an example: $i"
  fi

done
